name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: sudo apt-get update && sudo apt-get install libx11-dev libxi-dev libxkbcommon-dev
    - name: Build
      run: make
